# Generated by Django 4.2.1 on 2023-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('status', models.CharField(max_length=5, verbose_name='Статус')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='Дедлайн')),
            ],
        ),
    ]
