# Generated by Django 4.2.1 on 2023-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
